### ISSUE TITLE
ReferenceError: document is not defined in plyr-react

### ISSUE THREAD

**Issue by Clueed** [heyxyz/hey#3960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Following the local development steps (that worked fine before lensv2), the frontend errors out:

```sh
@hey/web:dev: cache bypass, force executing 2b906c3a6686733d
@hey/web:dev: 
@hey/web:dev: > @hey/web@0.0.0 dev /Users/user/dev/hey/apps/web
@hey/web:dev: > next dev --port 4783
@hey/web:dev: 
@hey/web:dev:    ▲ Next.js 14.0.1
@hey/web:dev:    - Local:        http://localhost:4783
@hey/web:dev:    - Experiments (use at your own risk):
@hey/web:dev:      · scrollRestoration
@hey/web:dev: 
@hey/web:dev:  ✓ Ready in 1700ms
@hey/web:dev:  ○ Compiling / ...
@hey/web:dev:  ✓ Compiled / in 13.6s (4939 modules)
@hey/web:dev: Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?
@hey/web:dev: (node:89010) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
@hey/web:dev: (Use `node --trace-deprecation ...` to show where the warning was created)
@hey/web:dev: ReferenceError: document is not defined
@hey/web:dev:     at /Users/user/dev/hey/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:302:21
@hey/web:dev:     at /Users/user/dev/hey/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:311:5
@hey/web:dev:     at /Users/user/dev/hey/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:2:83
@hey/web:dev:     at Object.<anonymous> (/Users/user/dev/hey/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:5:3)
@hey/web:dev:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
@hey/web:dev:     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
@hey/web:dev:     at Module.load (node:internal/modules/cjs/loader:1207:32)
@hey/web:dev:     at Module._load (node:internal/modules/cjs/loader:1023:12)
@hey/web:dev:     at cjsLoader (node:internal/modules/esm/translators:345:17)
@hey/web:dev:     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
@hey/web:dev:     at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
@hey/web:dev:     at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
@hey/web:dev:     at async importModuleDynamicallyWrapper (node:internal/vm/module:430:15)
@hey/web:dev: ReferenceError: document is not defined
@hey/web:dev:     at /Users/user/dev/hey/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:302:21
@hey/web:dev:     at /Users/user/dev/hey/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:311:5
@hey/web:dev:     at /Users/user/dev/hey/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:2:83
@hey/web:dev:     at Object.<anonymous> (/Users/user/dev/hey/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:5:3)
@hey/web:dev:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
@hey/web:dev:     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
@hey/web:dev:     at Module.load (node:internal/modules/cjs/loader:1207:32)
@hey/web:dev:     at Module._load (node:internal/modules/cjs/loader:1023:12)
@hey/web:dev:     at cjsLoader (node:internal/modules/esm/translators:345:17)
@hey/web:dev:     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
@hey/web:dev:     at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
@hey/web:dev:     at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
@hey/web:dev:     at async importModuleDynamicallyWrapper (node:internal/vm/module:430:15)
@hey/web:dev:  ⨯ unhandledRejection: ReferenceError: document is not defined
@hey/web:dev:     at /Users/user/dev/hey/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:302:21
@hey/web:dev:     at /Users/user/dev/hey/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:311:5
@hey/web:dev:     at /Users/user/dev/hey/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:2:83
@hey/web:dev:     at Object.<anonymous> (/Users/user/dev/hey/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:5:3)
@hey/web:dev:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
@hey/web:dev:     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
@hey/web:dev:     at Module.load (node:internal/modules/cjs/loader:1207:32)
@hey/web:dev:     at Module._load (node:internal/modules/cjs/loader:1023:12)
@hey/web:dev:     at cjsLoader (node:internal/modules/esm/translators:345:17)
@hey/web:dev:     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
@hey/web:dev:     at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
@hey/web:dev:     at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
@hey/web:dev:     at async importModuleDynamicallyWrapper (node:internal/vm/module:430:15)
@hey/web:dev:  ⨯ unhandledRejection: ReferenceError: document is not defined
@hey/web:dev:     at /Users/user/dev/hey/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:302:21
@hey/web:dev:     at /Users/user/dev/hey/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:311:5
@hey/web:dev:     at /Users/user/dev/hey/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:2:83
@hey/web:dev:     at Object.<anonymous> (/Users/user/dev/hey/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:5:3)
@hey/web:dev:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
@hey/web:dev:     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
@hey/web:dev:     at Module.load (node:internal/modules/cjs/loader:1207:32)
@hey/web:dev:     at Module._load (node:internal/modules/cjs/loader:1023:12)
@hey/web:dev:     at cjsLoader (node:internal/modules/esm/translators:345:17)
@hey/web:dev:     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
@hey/web:dev:     at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
@hey/web:dev:     at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
@hey/web:dev:     at async importModuleDynamicallyWrapper (node:internal/vm/module:430:15)
```

### Expected Behavior

No errors on start and usable web app.

### Steps To Reproduce

```sh
git clone https://github.com/heyxyz/hey
cd hey
pnpm install
pnpm dev
```

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Chrome, Firefox, Brave, Safari, Edge, Others

### Anything else?

This is a relevant issues with no solution: https://github.com/chintan9/plyr-react/issues/1119

**Comment by bigint** [comment]
This is weird, still happening to you? tried from new fork?
